export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const CHECK_TODO = 'CHECK_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const CHECK_ALL_TODOS = 'CHECK_ALL_TODOS'
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED'
export const FILTERED_TODOS = 'FILTERED_TODOS'
export const CHANGE_FILTER = 'CHANGE_FILTER'

export const GET_CLICK = 'GET_CLICK'